version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/saas-app/
hooks:
  BeforeInstall:
    - location: deploy/stop_server.sh
      timeout: 120
      runas: root
  AfterInstall:
    - location: deploy/init_system.sh
      timeout: 300
      runas: root
    - location: deploy/config_app.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/start_server.sh
      timeout: 120
      runas: root
